{
  "id": "CVE-2025-8194",
  "sourceIdentifier": "cna@python.org",
  "published": "2025-07-28T19:15:43.793",
  "lastModified": "2025-07-28T20:17:49.123",
  "vulnStatus": "Received",
  "descriptions": [
    {
      "lang": "en",
      "value": "There is a defect in the CPython “tarfile” module affecting the “TarFile” extraction and entry enumeration APIs. The tar implementation would process tar archives with negative offsets without error, resulting in an infinite loop and deadlock during the parsing of maliciously crafted tar archives. \n\nThis vulnerability can be mitigated by including the following patch after importing the “tarfile” module:\n\n\n\nimport tarfile\n\ndef _block_patched(self, count):\n    if count \u003c 0:  # pragma: no cover\n        raise tarfile.InvalidHeaderError(\"invalid offset\")\n    return _block_patched._orig_block(self, count)\n\n_block_patched._orig_block = tarfile.TarInfo._block\ntarfile.TarInfo._block = _block_patched"
    }
  ],
  "metrics": {
    "cvssMetricV31": [
      {
        "source": "cna@python.org",
        "type": "Secondary",
        "cvssData": {
          "version": "3.1",
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
          "attackVector": "NETWORK",
          "attackComplexity": "LOW",
          "privilegesRequired": "NONE",
          "userInteraction": "NONE",
          "scope": "UNCHANGED",
          "confidentialityImpact": "NONE",
          "integrityImpact": "NONE",
          "availabilityImpact": "HIGH",
          "baseScore": 7.5,
          "baseSeverity": "HIGH"
        },
        "exploitabilityScore": 3.9,
        "impactScore": 3.6
      }
    ]
  },
  "weaknesses": [
    {
      "source": "cna@python.org",
      "type": "Secondary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-835"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://github.com/python/cpython/commit/7040aa54f14676938970e10c5f74ea93cd56aa38",
      "source": "cna@python.org"
    },
    {
      "url": "https://github.com/python/cpython/commit/cdae923ffe187d6ef916c0f665a31249619193fe",
      "source": "cna@python.org"
    },
    {
      "url": "https://github.com/python/cpython/issues/130577",
      "source": "cna@python.org"
    },
    {
      "url": "https://github.com/python/cpython/pull/137027",
      "source": "cna@python.org"
    },
    {
      "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/ZULLF3IZ726XP5EY7XJ7YIN3K5MDYR2D/",
      "source": "cna@python.org"
    }
  ]
}