{
  "id": "CVE-2025-32414",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2025-04-08T03:15:15.940",
  "lastModified": "2025-04-08T03:15:15.940",
  "vulnStatus": "Received",
  "descriptions": [
    {
      "lang": "en",
      "value": "In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds memory access can occur in the Python API (Python bindings) because of an incorrect return value. This occurs in xmlPythonFileRead and xmlPythonFileReadRaw because of a difference between bytes and characters."
    }
  ],
  "metrics": {
    "cvssMetricV31": [
      {
        "source": "cve@mitre.org",
        "type": "Secondary",
        "cvssData": {
          "version": "3.1",
          "vectorString": "CVSS:3.1/AV:L/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:L",
          "attackVector": "LOCAL",
          "attackComplexity": "HIGH",
          "privilegesRequired": "NONE",
          "userInteraction": "NONE",
          "scope": "CHANGED",
          "confidentialityImpact": "LOW",
          "integrityImpact": "LOW",
          "availabilityImpact": "LOW",
          "baseScore": 5.6,
          "baseSeverity": "MEDIUM"
        },
        "exploitabilityScore": 1.4,
        "impactScore": 3.7
      }
    ]
  },
  "weaknesses": [
    {
      "source": "cve@mitre.org",
      "type": "Secondary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-393"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://gitlab.gnome.org/GNOME/libxml2/-/issues/889",
      "source": "cve@mitre.org"
    }
  ]
}