{
  "id": "CVE-2024-25178",
  "sourceIdentifier": "cve@mitre.org",
  "published": "2025-07-07T17:15:27.527",
  "lastModified": "2025-07-08T18:15:25.760",
  "vulnStatus": "Awaiting Analysis",
  "descriptions": [
    {
      "lang": "en",
      "value": "LuaJIT through 2.1 has an out-of-bounds read in the stack-overflow handler in lj_state.c"
    },
    {
      "lang": "es",
      "value": "LuaJIT hasta la versión 2.1 tiene una lectura fuera de los límites en el controlador de desbordamiento de pila en lj_state.c"
    }
  ],
  "metrics": {
    "cvssMetricV31": [
      {
        "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
        "type": "Secondary",
        "cvssData": {
          "version": "3.1",
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H",
          "attackVector": "NETWORK",
          "attackComplexity": "LOW",
          "privilegesRequired": "NONE",
          "userInteraction": "NONE",
          "scope": "UNCHANGED",
          "confidentialityImpact": "HIGH",
          "integrityImpact": "NONE",
          "availabilityImpact": "HIGH",
          "baseScore": 9.1,
          "baseSeverity": "CRITICAL"
        },
        "exploitabilityScore": 3.9,
        "impactScore": 5.2
      }
    ]
  },
  "weaknesses": [
    {
      "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
      "type": "Secondary",
      "description": [
        {
          "lang": "en",
          "value": "CWE-125"
        }
      ]
    }
  ],
  "references": [
    {
      "url": "https://gist.github.com/pwnhacker0x18/423b4292f301ab274b42d5ed6e0b87d8",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/LuaJIT/LuaJIT/commit/defe61a56751a0db5f00ff3ab7b8f45436ba74c8",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/LuaJIT/LuaJIT/issues/1152",
      "source": "cve@mitre.org"
    },
    {
      "url": "https://github.com/LuaJIT/LuaJIT/issues/1152",
      "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0"
    }
  ]
}